### ISSUE TITLE
Create an AWS IoT Service

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel#131]
So that we can define rights to call IoT from other services like lambda functions.

**Comment by pauldeden** [comment]
Here's an example from https://github.com/byu-oit/aws-iot-physical-facilities

```
  IoTTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: iot_physical_facilities_rule
      TopicRulePayload:
        Actions:
          - Lambda:
              FunctionArn: !GetAtt IoTPhysicalFacilitiesLambda.Arn
        AwsIotSqlVersion: '2015-10-08'
        RuleDisabled: false
        Sql: "SELECT * FROM 'iotbutton/#'" 
```

**Comment by pauldeden** [comment]
Once this is done we can add this to handel.yml in https://github.com/byu-oit/aws-iot-physical-facilities

**Comment by dsw88** [comment]
This has been implemented. The initial support doesn't cover all of IoT, but does have support for creating topic rules that fire Lambdas, which is what we currently need.

The ReadTheDocs site is currently having some issues building new versions of docs, so the IoT documentation doesn't show up there, but hopefully will by tomorrow.

**Comment by dsw88** [comment]
In case the site doesn't come back up, here's a short example showing how to use the service:
```
version: 1

name: my-iot-test

environments:
  dev:
    topicrule:
      type: iot
      event_consumers:
      - service_name: function
        sql: "SELECT * FROM 'iotbutton/#'"
        rule_disabled: true
    function:
      type: lambda
      path_to_code: .
      handler: index.handler
      runtime: nodejs6.10
```
