### ISSUE TITLE
S6 - Add support for service ... or is it already there

### ISSUE THREAD

**Issue by tomdavidson** [byu-oit/handel#180]
I created a simple secret tool, [s6](https://td7x.gitlab.io/s6/), that uses S3.  Previously I looked at Handel with the expectation of integration but on-face there doesn't seem to be any need.

Currently, Handel can provision a bucket and include read access to the bucket via IAM for the app.  S6 then runs outside of Handel using the provisioned bucket.

S6 is not a provisioner... so there does not seem to be the need for explicit integration or support, but maybe that is just my lack of experience with Handel. @dsw88 what do you think?

**Comment by dsw88** [comment]
This S6 tool looks like it would work with the implemented services in Handel. Here's an example configuration that would work with this:

```
version: 1

name: my-s6-app

environments:
  dev:
    webapp:
      type: beanstalk
      # Any required beanstalk params here
      dependencies:
      - bucket
    bucket:
      type: s3
```

The above will provision a Beanstalk that has an S3 bucket wired up to talk to it. This bucket can be used for storing the app's secrets with S6, plus any other type of data the app needs to store. Because the permissions are wired up for you, the S6 tool ought to be able to be used from the code in Beanstalk with no additional work.

For populating the secrets.json file iteself in the bucket, BYU's PowerUser role ought to give you permissions to use S6 to put that file to the bucket. 

Assuming I've understood how to use S6 correctly from the docs, it does seem like all the pieces are there to use it with Handel.
