### ISSUE TITLE
SNS - support the endpoint and protocol cloudformation attributes

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel#195]
I would like to create an SNS topic with Handel and have it create the endpoint and protocol for me as IAC (instead of me having to manually configure the topic after it is created by handel).

Here is an example of how it could look
```
type: sns
  subscription:        
    endpoint: "email@email.com"
    protocol: "email"
```
