### ISSUE TITLE
Route53 Support

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/handel#237]
Here's what I'm proposing:

One - a new resource type, `route53zone`, representing a hosted zone in Route 53.  It would look something like this:

```yaml
my-hosted-zone:
  type: route53zone
  name: mydomain.byu.edu
  private: true #default to false
  vpcs: #required if private=true, cannot be specified if private=false.
    - vpc12312312
    - <account> #Uses default vpc from account config
```

Then, we can enhance the configuration of types that are valid DNS alias targets with a DNS configuration.  Using an ECS resource as an example, it could look like:

```yaml
my-ecs:
  type: ecs
  ...
  dns:
    name: mysubdomain.byu.edu
    protocols: [ ipv4, ipv6 ] #Or should we change this to be record_types: [ A, AAAA ]?
    comment: some comment
  dependencies:
    - my-hosted-zone
```

This would create A and AAAA records on the specified hosted zone, depending on which protocols are enabled. The default should be both, but may vary depending on what's supported by the service they're fronting. I could even make a case for us not giving the user any choice, and just setting up whichever records are supported by the backend service. 
The records would, in this case, point to the load balancer that is created to front the ECS service.

Here's a list of current service that could receive this enhancement:

* API Gateway (this would require adding support for custom domains)
* Beanstalk
* ECS
* S3 Static Site (this might require adding cloudfront support)

Theoretically, we could also expose RDS instances too, but I think we should always limit those to private zones.

As an additional rule, we could say that public zones (the default) must be a subdomain of byu.edu, but private zones can be whatever (since they just set up DNS rules in the specified VPCs).

If this looks good to you, I can start working on implementing it.  I'd like to get it out there soon, so that I can take advantage of it.
