### ISSUE TITLE
Add support for DynamoDB AutoScaling

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/handel#273]
You can autoscale provisioned throughput now!

There's an example available at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalabletarget.html#aws-resource-applicationautoscaling-scalabletarget-ddb-example

I may be able to work on this over the next week.

**Comment by dsw88** [comment]
Awesome! I moved this onto the roadmap.

**Comment by ThatJoeMoore** [comment]
What do you think about this for the config:

```yml
  my_table:
    type: dynamodb
    provisioned_throughput:
      read_capacity_units: 1
      write_capacity_units: 1
      #Autoscaling-specific
      autoscaling: enabled
      max_write_capacity_unit: 10
      min_write_capacity_unit: 1
      write_target_utilization: 50%
      max_read_capacity_unit: 10
      min_read_capacity_unit: 1
      read_target_utilization: 50%

     apply_to_global_indexes: true
```

Then, the same autoscaling properties would be available for each global index, or you can set apply_to_global_indexes to copy these settings over to all of them.  Or, I suppose we could get rid of that flag and just have the global indexes default to match the table settings.

@dsw88 What do you think?

**Comment by dsw88** [comment]
How about a simplification like this?
```
my_table:
  type: dynamodb
  provisioned_throughput:
    read_capacity_units: 1-10 # If single number specified, autoscaling is disabled. If range, autoscaling enabled with min-max
    write_capacity_units: 1-10 # Same as above
    write_target_utilization: 50 # Value is in percent. Default: 50 if not specified and autoscaling enabled.
    read_target_utilization: 50 # Value is in percent. Same default as above.
```
That's a little different than what we've done with min/max elsewhere, but then there autoscaling is always enabled, where here it is not, and there's two min/max values instead of one. So maybe using a range syntax like this would be a bit nicer for this service?
