### ISSUE TITLE
API Gateway - Support custom domains and BasePath mappings

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/handel#347]
APIGW allows you to setup up custom domain name DNS entry/certificate pairs and create a mapping from them to an API/stage pair.  One can associate multiple APIs/stages with a single custom domain name using a base path - IE, you could route to API A / Stage Prod with `https://myapi.example.com/api-a-prod` and API B / Stage Beta with `https://myapi.example.com/api-b-beta`, etc - all off of the same domain name.

I'd like us to support setting up these kinds of mappings.

So, the dependency graph between the moving parts here is like this:

![domain](https://user-images.githubusercontent.com/455981/34699340-f655cf1c-f499-11e7-9f9d-7ed243cdec0c.png)

The most straightforward way to set this up (though it may not be the easiest way due to the code structure) is to only allow one domain name and base path mapping per API Gateway service.  So, it would look like this:

```yaml
  type: apigateway
  proxy: ...
  base_path:
    dns_name: myapi.example.com
    path: /mypath # default: /
    certificate_id: arn:a:b:c:d
```

We could also easily allow mapping multiple base paths per api by making that an array.

Another option would be to have a new service like `apigateway_custom_domain` which, combined with a `base_path` attribute on the gateway, would allow us to map multiple different APIs onto the same domain:

```yaml
custom-domain:
  type: apigateway_custom_domain
  dns_name: myapi.example.com
  certificate_id: arn:a:b:c:d

api-a:
  type: apigateway
  proxy: ...
  base_paths:
  - domain: custom-domain
     path: /api-a

api-b:
  type: apigateway
  proxy: ...
  base_paths:
  - domain: custom-domain
     path: /api-b

```

We could also allow both - easily configure the custom domain using the dns_name and certificate_id, or referencing a shared one using the `domain` or `custom_domain` or something.

I can do the implementation (as I need it soon-ish), but what do you think about the different configuration options?

**Comment by ThatJoeMoore** [comment]
@dsw88 any thoughts?

**Comment by dsw88** [comment]
As I look at this I'm liking your first option best because of its simplicity:
```
type: apigateway
proxy: ...
base_path:
  dns_name: myapi.example.com
  path: /mypath # default: /
  certificate_id: arn:a:b:c:d
```
The only thing I would change is the "base_path" parameter name, since that doesn't seem to represent what is under it fully, because you're both specifying a custom DNS name and a base path on that name. I unfortunately don't know what I would call it though. :) Something like "custom_domain"? I don't know that I like that one either though. :)

What do you think about option 1 though, is it too constraining? I like it because of its ease of configuration as well as implementation.
