### ISSUE TITLE
Inject parameters as environment variables if they are within the application's scope.

### ISSUE THREAD

**Issue by saholman** [byu-oit/handel#427]
We should be able to reference parameter store items in the handel file when setting environment variables. Something like:

```yml
name: my-awesome-app
...
environment_variables:
  DB_PASSWORD: "ssm:DB_PASSWORD"
```
where the parameter looks like `my-awesome-app.dev.DB_PASSWORD`
