### ISSUE TITLE
ECS - Make check require both container 'routing' and 'load_balancer' sections to be specified together.

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#480]
Someone used this expecting a load balancer to be created:
```
version: 1

name: appname

environments:
    dev:
        app:
            type: ecs-fargate
            containers:
             - name: containername
                image_name: user/imagename:latest
            auto_scaling:
                min_tasks: 1
                max_tasks: 1
            load_balancer:
                type: http
```

It passed `handel check`, but should have probably given an error saying they had to specify the `routing` section.
