### ISSUE TITLE
Event consumers check produces bad error message

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#528]
When checking this Handel file, an error occurred:

```
version: 1

name: dynamodb-test

environments:
  dev:
    webapp:
      type: dynamodb
      table_name: exampletablename
      partition_key:
        name: partitionKeyName
        type: Number
      sort_key:
        name: sortKeyName
        type: String
      provisioned_throughput:
        read_capacity_units: 5
        write_capacity_units: 5
      event_consumers:
      - service_name: function
        batch_size: 100
      tags:
        mytagname: mytagvalue
```

The event_consumers points to a non-existent service, and should show an error saying something like 'The service doesn't exist that you are trying to produce events to' or something like that. Instead, you get this error:

```
error:   Error occurred during check: Cannot read property 'type' of undefined
error:   TypeError: Cannot read property 'type' of undefined
    at checkEventConsumers (/Users/dsw88/projects/byu/handel/handel/dist/handelfile/parser-v1.js:148:103)
    at Object.<anonymous> (/Users/dsw88/projects/byu/handel/handel/dist/handelfile/parser-v1.js:187:40)
    at Generator.next (<anonymous>)
    at /Users/dsw88/projects/byu/handel/handel/dist/handelfile/parser-v1.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dsw88/projects/byu/handel/handel/dist/handelfile/parser-v1.js:3:12)
    at Object.validateHandelFile (/Users/dsw88/projects/byu/handel/handel/dist/handelfile/parser-v1.js:170:12)
    at /Users/dsw88/projects/byu/handel/handel/dist/cli/index.js:83:47
    at Generator.next (<anonymous>)
    at /Users/dsw88/projects/byu/handel/handel/dist/cli/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dsw88/projects/byu/handel/handel/dist/cli/index.js:3:12)
    at validateHandelFile (/Users/dsw88/projects/byu/handel/handel/dist/cli/index.js:82:12)
    at /Users/dsw88/projects/byu/handel/handel/dist/cli/index.js:285:15
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dsw88/projects/byu/handel/handel/dist/cli/index.js:4:58)
```
